#!/bin/bash

REPOSITORY="$1"
BRANCH="$5"
BUILD_ORG_NAME="dafire"

REPO_PATH="/home/git/repo/"
if [ -d "$REPO_PATH" ]; then rm -rf "$REPO_PATH"; fi
mkdir -p "$REPO_PATH" && cat | tar -x -C "$REPO_PATH"

BASE=`basename $REPOSITORY .git`
if [ "$BRANCH" != "master" ]
then
  BASE="$BASE-$BRANCH"
fi

mydeploy --base "$BASE" create --repo "$REPO_PATH"

rc=$?
if [[ $rc != 0 ]] ; then
  echo "python script failed - exiting."
  exit $rc
fi